"""Builder-side constants (TouchDesigner network layout)."""
import os

from performance_grid.paths import ROOT
from performance_grid.ui_theme import (  # noqa: F401
    CELL_BG_IDLE_B,
    CELL_BG_IDLE_G,
    CELL_BG_IDLE_R,
    CELL_BG_SELECTED_B,
    CELL_BG_SELECTED_G,
    CELL_BG_SELECTED_R,
    CELL_NAME_FONT_SIZE,
    CELL_RING_CB,
    CELL_RING_CG,
    CELL_RING_CR,
    CELL_RING_IDLE_CB,
    CELL_RING_IDLE_CG,
    CELL_RING_IDLE_CR,
    CELL_RING_IDLE_W,
    CELL_RING_PAD,
    CELL_RING_W,
    EMPTY_CELL_B,
    EMPTY_CELL_G,
    EMPTY_CELL_R,
    GRID_FONT,
    GRID_FONT_SIZE,
    SCENE_ACTIVE_TEXT,
    SCENE_BAR_BG_ALPHA,
    SCENE_BTN_TILE_BG,
    SCENE_BTN_TOPFILL,
    SCENE_CONTROL_BG_ALPHA,
    SCENE_CONTROL_TILE_ALPHA,
    SCENE_IDLE_TEXT,
    TD_BG_HEADER,
    TD_BG_INPUT,
    TD_BG_MAIN,
    TD_FONT,
    TD_SLIDER_THUMB,
    TD_SLIDER_TRACK,
    TD_TEXT_ACTIVE,
    TD_TEXT_LABEL,
    UI_NAME_BAR_BG,
    UI_PREVIEW_BG,
    UI_TEXT_PRIMARY,
    UI_TEXT_SECONDARY,
)

DEFAULT_COMP = '/project1/performance_mode'
SETTINGS_COMP = '/settings'
PROGRAM_PICK_COMP = '/program_pick'
_SETTINGS_OP = 'op("{0}")'.format(SETTINGS_COMP)
DEFAULT_TOX = os.path.join(ROOT, 'tox', 'touchengine', 'performance_mode.tox')
DEFAULT_STROBE_TOX = os.path.join(ROOT, 'tox', 'touchengine', 'strobe_slices.tox')
DEFAULT_CANVAS_W = 1920
DEFAULT_CANVAS_H = 1080
DEFAULT_CANVAS_BG_R = 0.0
DEFAULT_CANVAS_BG_G = 0.0
DEFAULT_CANVAS_BG_B = 0.0
CANVAS_PRESET_NAMES = ['1920x1080', '1080x1920', '1080x1080']
DEFAULT_FADE_ACTIVE = False
DEFAULT_CELL_CROSSFADE = True
DEFAULT_COLUMN_CROSSFADE = True
DEFAULT_COLUMN_CROSSFADE_DUR = 1.0
PULSE_SLOTS = 6
DEFAULT_OSC_IP = '127.0.0.1'
SETS_SUBDIR = 'sets'
SETS_VERSION = 1
DEFAULT_SET_FILENAME = 'performance_set.json'
DEFAULT_SET_NAME = 'performance_set'

CANVAS_W_EXPR = _SETTINGS_OP + '.par.Canvaswidth'
CANVAS_H_EXPR = _SETTINGS_OP + '.par.Canvasheight'
CANVAS_BG_R_EXPR = _SETTINGS_OP + '.par.Canvasbgr'
CANVAS_BG_G_EXPR = _SETTINGS_OP + '.par.Canvasbgg'
CANVAS_BG_B_EXPR = _SETTINGS_OP + '.par.Canvasbgb'

NUM_LAYERS = 4
MIN_LAYERS = 4
MAX_LAYERS = 9
DEFAULT_LAYERS = 4
NUM_COLS = 30
VISIBLE_COLS = 16
VISIBLE_ROWS = 9
CELL_LABEL_H = 16
CELL_H = 64
CELL_W = 128
CELL_GAP = 2
CELL_ASPECT = 16.0 / 9.0
CELL_TOPFILL = 'best'
ROW_LABEL_W = 72
ROW_OPACITY_W = 14
ROW_OPACITY_FADER_W = 58
ROW_OPACITY_HDR_W = 58
ROW_OPACITY_RIGHT_PAD = 14
UI_W = 1920
UI_H = 1080
SETTINGS_PANEL_EXTRA_W = 80
PREVIEW_W = UI_W // 2 - SETTINGS_PANEL_EXTRA_W
UI_PANEL_W = UI_W - PREVIEW_W
UI_PANEL_X = PREVIEW_W
GRID_VIEW_W = UI_W
BOTTOM_ZONE_MIN = 360
GRID_X0 = ROW_LABEL_W + ROW_OPACITY_HDR_W + CELL_GAP + ROW_OPACITY_RIGHT_PAD + CELL_GAP
CELL_THUMB_H = CELL_H - CELL_LABEL_H
PARAM_PANEL_H = 220
SETTINGS_PANEL_MIN_W = 320
SETTINGS_TAB_GRID_OSC = 'GrdOSC'
SETTINGS_TAB_PERF = 'Perf'
SETTINGS_TAB_GRID_OSC_LEGACY = ('Grid OSC', 'GRID OSC')
MIN_SCENES = 1
MAX_SCENES = 32
DEFAULT_SCENES = 1
SCENE_BTN_W = 28
SCENE_BTN_H = 22
# Raster size before UI downscale (>=3× button size avoids jagged edges).
TRANSPORT_ICON_PX = 64
TRANSPORT_ICON_SCALE = 0.42
SCENE_BAR_H = 26
SCENE_BAR_TOP_PAD = 12
SCENE_BAR_CONTENT_Y = 4
SCENE_BAR_LOGO_PAD = 8
SCENE_BAR_LOGO_TEXT_W = 36  # approx width of centered Layer / L# labels in ROW_LABEL_W
SCENE_BAR_LOGO_X = max(SCENE_BAR_LOGO_PAD, (ROW_LABEL_W - SCENE_BAR_LOGO_TEXT_W) // 2)
SCENE_BAR_LOGO_GAP = 10
SCENE_BAR_LOGO_Y_NUDGE = 1
LOGO_NATURAL_W = 300
LOGO_NATURAL_H = 52
LOGO_H = 18
LOGO_W = int(round(LOGO_H * LOGO_NATURAL_W / LOGO_NATURAL_H))
SCENE_GRID_GAP = 12
GRID_HDR_H = 30
GRID_HDR_PAD = 2

VIDEO_EXTS = {
    '.mp4', '.mov', '.avi', '.mkv', '.webm', '.m4v', '.wmv',
    '.mpg', '.mpeg', '.mxf', '.gif', '.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp', '.webp',
}
VALID_CLIP_TYPES = ('video', 'tox')
